name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Format check
      run: cargo fmt -- --check
    - name: Build (no features)
      run: cargo build --no-default-features --verbose
    - name: Build (all features)
      run: cargo build --all-features --verbose
    - name: Test (no features)
      run: PROPTEST_CASES=100000 cargo test --verbose --no-default-features || cat proptest-regressions/base.txt
    - name: Test (all features)
      run: PROPTEST_CASES=100000 cargo test --verbose --all-features || cat proptest-regressions/base.txt
    - name: Clippy (no features)
      run: cargo clippy --all-targets --verbose --no-default-features
    - name: Clippy (all features)
      run: cargo clippy --all-targets --verbose --all-features
